apiVersion: v1
kind: Service
metadata:
  name: helloworld-go-svc
  labels:
    app: helloworld-go
spec:
  # Valid values for the ServiceType field are:
  # ClusterIP:    use a cluster-internal IP only - this is the default and is discussed above. Choosing this value means that you want this service to be
  #               reachable only from inside of the cluster.
  # NodePort:     on top of having a cluster-internal IP, expose the service on a port on each node of the cluster (the same port on each node). You'll be
  #               able to contact the service on any <NodeIP>:NodePort address.
  # LoadBalancer: on top of having a cluster-internal IP and exposing service on a NodePort also, ask the cloud provider for a load balancer which
  #               forwards to the Service exposed as a <NodeIP>:NodePort for each Node.
  type: NodePort
  ports:
    # the port that this service should serve on. This port is only accessible from inside the kubernetes cluster
  - port: 80
    # the port of the target pod that the service will route the traffic to
    targetPort: 80
    # the external port expose on all kube nodes. This port is accessible from outside by using any node ip
    # nodePort: 8080
  # label keys and values that must match in order to receive traffic for this service
  selector:
    app: helloworld-go
