apiVersion: apps/v1beta1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: helloworld-go-deployment
  labels:
    app: helloworld-go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld-go
  template:
    metadata:
      labels:
        app: helloworld-go
    spec:
      containers:
      - name: helloworld-go
        image: evanscastonguay/helloworld-go
        ports:
        - containerPort: 80
        env:
        - name: version
          value: "2"
